// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ProofPath.Infrastructure.Persistence;

#nullable disable

namespace ProofPath.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ProofPathDbContext))]
    partial class ProofPathDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.DataProtection.EntityFrameworkCore.DataProtectionKey", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("FriendlyName")
                        .HasColumnType("text");

                    b.Property<string>("Xml")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("DataProtectionKeys");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .HasColumnType("text");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("ProofPath.Domain.Entities.AnalysisJob", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Attempts")
                        .HasColumnType("integer");

                    b.Property<DateTime>("AvailableAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CandidateProfileId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ErrorCode")
                        .HasColumnType("text");

                    b.Property<string>("InputVersion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("LeaseExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("LeaseToken")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ResourceId")
                        .HasColumnType("uuid");

                    b.Property<string>("ResultJson")
                        .HasColumnType("jsonb");

                    b.Property<bool>("Retryable")
                        .HasColumnType("boolean");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("State", "AvailableAt");

                    b.HasIndex("CandidateProfileId", "Kind", "ResourceId", "InputVersion")
                        .IsUnique();

                    b.ToTable("AnalysisJobs");
                });

            modelBuilder.Entity("ProofPath.Domain.Entities.BehavioralEvidenceItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Basis")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("CandidateProfileId")
                        .HasColumnType("uuid");

                    b.Property<string>("Quote")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("ResumeExtractionId")
                        .HasColumnType("uuid");

                    b.Property<string>("SourceBlockId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Statement")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Strength")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ThemeKey")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("UserCorrected")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("CandidateProfileId");

                    b.HasIndex("ResumeExtractionId");

                    b.ToTable("BehavioralEvidenceItems");
                });

            modelBuilder.Entity("ProofPath.Domain.Entities.CandidateFact", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CandidateProfileId")
                        .HasColumnType("uuid");

                    b.Property<string>("Detail")
                        .HasColumnType("text");

                    b.Property<string>("EndDateText")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Organization")
                        .HasColumnType("text");

                    b.Property<string>("Quote")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("ResumeExtractionId")
                        .HasColumnType("uuid");

                    b.Property<string>("SourceBlockId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("StartDateText")
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .HasColumnType("text");

                    b.Property<bool>("UserCorrected")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("CandidateProfileId");

                    b.HasIndex("ResumeExtractionId");

                    b.ToTable((string)null);

                    b.UseTpcMappingStrategy();
                });

            modelBuilder.Entity("ProofPath.Domain.Entities.CandidateProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EducationSummary")
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .HasColumnType("text");

                    b.Property<string>("Headline")
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .HasColumnType("text");

                    b.Property<string>("Location")
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("WorkAuthorization")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("CandidateProfiles");
                });

            modelBuilder.Entity("ProofPath.Domain.Entities.ConnectedAccount", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CandidateProfileId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ConnectedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DisconnectedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("ExternalAccountId")
                        .HasColumnType("bigint");

                    b.Property<string>("ExternalLogin")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CandidateProfileId", "Provider")
                        .IsUnique();

                    b.HasIndex("Provider", "ExternalAccountId")
                        .IsUnique();

                    b.ToTable("ConnectedAccounts");
                });

            modelBuilder.Entity("ProofPath.Domain.Entities.EvidenceItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CandidateProfileId")
                        .HasColumnType("uuid");

                    b.Property<string>("Context")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Detector")
                        .HasColumnType("text");

                    b.Property<string>("DetectorVersion")
                        .HasColumnType("text");

                    b.Property<int?>("EndLine")
                        .HasColumnType("integer");

                    b.Property<string>("EvidenceType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("ExtractionConfidence")
                        .HasPrecision(4, 3)
                        .HasColumnType("numeric(4,3)");

                    b.Property<string>("Lifecycle")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("ObservedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("OriginalTerm")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("ProjectId")
                        .HasColumnType("uuid");

                    b.Property<string>("Quote")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("RepositoryAnalysisId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ResumeExtractionId")
                        .HasColumnType("uuid");

                    b.Property<string>("RevisionSha")
                        .HasColumnType("text");

                    b.Property<string>("SkillId")
                        .HasColumnType("text");

                    b.Property<string>("SourceBlockId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SourcePath")
                        .HasColumnType("text");

                    b.Property<int?>("StartLine")
                        .HasColumnType("integer");

                    b.Property<string>("Strength")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("UserCorrected")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("CandidateProfileId");

                    b.HasIndex("ProjectId");

                    b.HasIndex("ResumeExtractionId");

                    b.HasIndex("SkillId");

                    b.HasIndex("RepositoryAnalysisId", "SkillId", "SourcePath", "Detector")
                        .IsUnique()
                        .HasFilter("\"RepositoryAnalysisId\" IS NOT NULL");

                    b.ToTable("EvidenceItems");
                });

            modelBuilder.Entity("ProofPath.Domain.Entities.GitHubConnectionAttempt", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CandidateProfileId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NonceHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("ProtectedPayload")
                        .IsRequired()
                        .HasMaxLength(4096)
                        .HasColumnType("character varying(4096)");

                    b.HasKey("Id");

                    b.HasIndex("CandidateProfileId");

                    b.HasIndex("ExpiresAt");

                    b.HasIndex("NonceHash")
                        .IsUnique();

                    b.ToTable("GitHubConnectionAttempts");
                });

            modelBuilder.Entity("ProofPath.Domain.Entities.GitHubInstallation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ConnectedAccountId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("InstallationId")
                        .HasColumnType("bigint");

                    b.Property<string>("PermissionsJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("RepositorySelection")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTime?>("SuspendedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("TargetAccountId")
                        .HasColumnType("bigint");

                    b.Property<string>("TargetLogin")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("TargetType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ConnectedAccountId")
                        .IsUnique();

                    b.HasIndex("InstallationId")
                        .IsUnique();

                    b.ToTable("GitHubInstallations");
                });

            modelBuilder.Entity("ProofPath.Domain.Entities.Job", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AnalysisJobId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CandidateProfileId")
                        .HasColumnType("uuid");

                    b.Property<string>("Company")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(50000)
                        .HasColumnType("character varying(50000)");

                    b.Property<int>("DescriptionVersion")
                        .HasColumnType("integer");

                    b.Property<string>("SourceUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Title")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CandidateProfileId", "UpdatedAt");

                    b.ToTable("Jobs");
                });

            modelBuilder.Entity("ProofPath.Domain.Entities.JobRequirement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("BehavioralThemeKey")
                        .HasColumnType("text");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("GroupKey")
                        .HasColumnType("text");

                    b.Property<string>("GroupType")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("Importance")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<bool>("IsEvaluable")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsScoreEligible")
                        .HasColumnType("boolean");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("NormalizationStatus")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)");

                    b.Property<string>("OriginalWording")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("QualifiersJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("Quote")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("RequirementSetId")
                        .HasColumnType("uuid");

                    b.Property<string>("SkillId")
                        .HasColumnType("text");

                    b.Property<string>("SkillTerm")
                        .HasColumnType("text");

                    b.Property<string>("SourceBlockId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<bool>("UserCorrected")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("SkillId");

                    b.HasIndex("RequirementSetId", "Key")
                        .IsUnique();

                    b.ToTable("JobRequirements");
                });

            modelBuilder.Entity("ProofPath.Domain.Entities.JobRequirementExtraction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ConfirmedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DescriptionVersion")
                        .HasColumnType("integer");

                    b.Property<string>("DraftJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("ExtractionVersion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("JobId")
                        .HasColumnType("uuid");

                    b.Property<string>("MachineJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NormalizationPolicyVersion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("Outdated")
                        .HasColumnType("boolean");

                    b.Property<string>("PromptVersion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Revision")
                        .HasColumnType("integer");

                    b.Property<string>("SchemaVersion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("JobId", "DescriptionVersion")
                        .IsUnique();

                    b.ToTable("JobRequirementExtractions");
                });

            modelBuilder.Entity("ProofPath.Domain.Entities.JobTracking", b =>
                {
                    b.Property<Guid>("JobId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("NextActionAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("Stage")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("JobId");

                    b.ToTable("JobTrackings");
                });

            modelBuilder.Entity("ProofPath.Domain.Entities.MatchRecommendation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<Guid>("MatchResultId")
                        .HasColumnType("uuid");

                    b.Property<int>("Rank")
                        .HasColumnType("integer");

                    b.Property<string>("Rationale")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<Guid?>("RequirementId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("MatchResultId", "Rank")
                        .IsUnique();

                    b.ToTable("MatchRecommendations");
                });

            modelBuilder.Entity("ProofPath.Domain.Entities.MatchResult", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CandidateProfileId")
                        .HasColumnType("uuid");

                    b.Property<string>("CandidateSnapshotJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("EvaluationCoverage")
                        .HasPrecision(6, 4)
                        .HasColumnType("numeric(6,4)");

                    b.Property<Guid>("JobId")
                        .HasColumnType("uuid");

                    b.Property<string>("OverallClassification")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<decimal>("OverallConfidence")
                        .HasPrecision(6, 4)
                        .HasColumnType("numeric(6,4)");

                    b.Property<decimal?>("OverallScore")
                        .HasPrecision(6, 2)
                        .HasColumnType("numeric(6,2)");

                    b.Property<string>("OverallStatus")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<Guid>("RequirementSetId")
                        .HasColumnType("uuid");

                    b.Property<string>("RequirementSnapshotJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("ResultJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("ScoringVersionId")
                        .IsRequired()
                        .HasColumnType("character varying(64)");

                    b.HasKey("Id");

                    b.HasIndex("RequirementSetId");

                    b.HasIndex("ScoringVersionId");

                    b.HasIndex("JobId", "CreatedAt");

                    b.ToTable("MatchResults");
                });

            modelBuilder.Entity("ProofPath.Domain.Entities.MatchingScoringVersion", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("ConfigurationJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Frozen")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.ToTable("MatchingScoringVersions");

                    b.HasData(
                        new
                        {
                            Id = "matching-v1",
                            ConfigurationJson = "{\"Version\":\"matching-v1\",\"TechnicalWeight\":0.45,\"EvidenceWeight\":0.25,\"ExperienceWeight\":0.25,\"EducationWeight\":0.05,\"WeakStrength\":0.3,\"ModerateStrength\":0.65,\"StrongStrength\":1,\"StaleFactor\":0.6,\"InactiveFactor\":0,\"RelatedScore\":0.35,\"WeakRelatedCap\":0.7,\"RequiredLevelFactor\":1,\"PreferredLevelFactor\":0.5,\"UnspecifiedLevelFactor\":0.5,\"CriticalImportance\":1.5,\"HighImportance\":1.2,\"MediumImportance\":1,\"LowImportance\":0.7,\"RequiredTechnicalWeight\":0.8,\"PreferredTechnicalWeight\":0.2,\"RelatedEvidenceFactor\":0.25,\"ExplicitExperienceWeight\":0.6,\"SeniorityWeight\":0.25,\"ResponsibilitiesWeight\":0.15,\"DegreeInProgressFactor\":0.65,\"MinimumComponentCoverage\":0.5,\"CoverageWarningThreshold\":0.6,\"CompleteCoverageThreshold\":0.8,\"BehavioralComponentEnabled\":false}",
                            CreatedAt = new DateTime(2026, 8, 31, 0, 0, 0, 0, DateTimeKind.Utc),
                            Frozen = true
                        });
                });

            modelBuilder.Entity("ProofPath.Domain.Entities.PrivateFileDeletion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Attempts")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("NextAttemptAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("StorageKey")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("StorageKey")
                        .IsUnique();

                    b.ToTable("PrivateFileDeletions");
                });

            modelBuilder.Entity("ProofPath.Domain.Entities.Repository", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CandidateProfileId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ConnectedAccountId")
                        .HasColumnType("uuid");

                    b.Property<string>("CoverageJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("DefaultBranch")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<long>("GitHubId")
                        .HasColumnType("bigint");

                    b.Property<string>("HtmlUrl")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<bool>("IncludedForAnalysis")
                        .HasColumnType("boolean");

                    b.Property<string>("LastRevisionSha")
                        .HasColumnType("text");

                    b.Property<DateTime?>("LastScanAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("LastSyncedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Owner")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<bool>("Private")
                        .HasColumnType("boolean");

                    b.Property<string>("ScanStatus")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.HasKey("Id");

                    b.HasIndex("ConnectedAccountId");

                    b.HasIndex("CandidateProfileId", "GitHubId")
                        .IsUnique();

                    b.HasIndex("CandidateProfileId", "IncludedForAnalysis");

                    b.ToTable("Repositories");
                });

            modelBuilder.Entity("ProofPath.Domain.Entities.RepositoryAnalysis", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AnalysisJobId")
                        .HasColumnType("uuid");

                    b.Property<string>("AnalysisPolicyVersion")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("CoverageJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ExtractionVersion")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<Guid>("RepositoryId")
                        .HasColumnType("uuid");

                    b.Property<string>("ResultJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("RevisionSha")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("ScanIdentity")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("WarningsJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.HasKey("Id");

                    b.HasIndex("AnalysisJobId")
                        .IsUnique();

                    b.HasIndex("RepositoryId");

                    b.HasIndex("ScanIdentity")
                        .IsUnique();

                    b.ToTable("RepositoryAnalyses");
                });

            modelBuilder.Entity("ProofPath.Domain.Entities.RequirementMatchEvidenceRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Contribution")
                        .HasPrecision(6, 4)
                        .HasColumnType("numeric(6,4)");

                    b.Property<Guid>("EvidenceItemId")
                        .HasColumnType("uuid");

                    b.Property<string>("EvidenceSnapshotJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<Guid>("RequirementMatchRecordId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RequirementMatchRecordId", "EvidenceItemId")
                        .IsUnique();

                    b.ToTable("RequirementMatchEvidenceRecords");
                });

            modelBuilder.Entity("ProofPath.Domain.Entities.RequirementMatchRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("MatchResultId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RequirementId")
                        .HasColumnType("uuid");

                    b.Property<string>("RequirementSnapshotJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("ResultSnapshotJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.HasKey("Id");

                    b.HasIndex("MatchResultId", "RequirementId")
                        .IsUnique();

                    b.ToTable("RequirementMatchRecords");
                });

            modelBuilder.Entity("ProofPath.Domain.Entities.RequirementSet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Active")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("ConfirmedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("JobId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("JobRequirementExtractionId")
                        .HasColumnType("uuid");

                    b.Property<int>("Version")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("JobRequirementExtractionId")
                        .IsUnique();

                    b.HasIndex("JobId", "Active")
                        .IsUnique()
                        .HasFilter("\"Active\" = true");

                    b.HasIndex("JobId", "Version")
                        .IsUnique();

                    b.ToTable("RequirementSets");
                });

            modelBuilder.Entity("ProofPath.Domain.Entities.Resume", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AnalysisJobId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CandidateProfileId")
                        .HasColumnType("uuid");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("Length")
                        .HasColumnType("bigint");

                    b.Property<string>("Sha256")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("StorageKey")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Version")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("StorageKey")
                        .IsUnique();

                    b.HasIndex("CandidateProfileId", "Version")
                        .IsUnique();

                    b.ToTable("Resumes");
                });

            modelBuilder.Entity("ProofPath.Domain.Entities.ResumeExtraction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Active")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("ConfirmedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DraftJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("ExtractionVersion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MachineJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PromptVersion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("ResumeId")
                        .HasColumnType("uuid");

                    b.Property<int>("Revision")
                        .HasColumnType("integer");

                    b.Property<string>("SchemaVersion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ResumeId")
                        .IsUnique();

                    b.ToTable("ResumeExtractions");
                });

            modelBuilder.Entity("ProofPath.Domain.Entities.Skill", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Skills");

                    b.HasData(
                        new
                        {
                            Id = "csharp",
                            DisplayName = "C#"
                        },
                        new
                        {
                            Id = "dotnet",
                            DisplayName = ".NET"
                        },
                        new
                        {
                            Id = "aspnet-core",
                            DisplayName = "ASP.NET Core"
                        },
                        new
                        {
                            Id = "entity-framework-core",
                            DisplayName = "Entity Framework Core"
                        },
                        new
                        {
                            Id = "react",
                            DisplayName = "React"
                        },
                        new
                        {
                            Id = "typescript",
                            DisplayName = "TypeScript"
                        },
                        new
                        {
                            Id = "javascript",
                            DisplayName = "JavaScript"
                        },
                        new
                        {
                            Id = "postgresql",
                            DisplayName = "PostgreSQL"
                        },
                        new
                        {
                            Id = "sql",
                            DisplayName = "SQL"
                        },
                        new
                        {
                            Id = "docker",
                            DisplayName = "Docker"
                        },
                        new
                        {
                            Id = "git",
                            DisplayName = "Git"
                        },
                        new
                        {
                            Id = "github-actions",
                            DisplayName = "GitHub Actions"
                        },
                        new
                        {
                            Id = "python",
                            DisplayName = "Python"
                        },
                        new
                        {
                            Id = "java",
                            DisplayName = "Java"
                        },
                        new
                        {
                            Id = "nodejs",
                            DisplayName = "Node.js"
                        },
                        new
                        {
                            Id = "express",
                            DisplayName = "Express"
                        },
                        new
                        {
                            Id = "rest-api",
                            DisplayName = "REST APIs"
                        },
                        new
                        {
                            Id = "dependency-injection",
                            DisplayName = "Dependency Injection"
                        },
                        new
                        {
                            Id = "authentication-authorization",
                            DisplayName = "Authentication & Authorization"
                        },
                        new
                        {
                            Id = "automated-testing",
                            DisplayName = "Automated Testing"
                        },
                        new
                        {
                            Id = "ci-cd",
                            DisplayName = "CI/CD"
                        },
                        new
                        {
                            Id = "aws",
                            DisplayName = "AWS"
                        });
                });

            modelBuilder.Entity("ProofPath.Domain.Entities.SkillAlias", b =>
                {
                    b.Property<string>("Alias")
                        .HasColumnType("text");

                    b.Property<string>("SkillId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Alias");

                    b.HasIndex("SkillId");

                    b.ToTable("SkillAliases");

                    b.HasData(
                        new
                        {
                            Alias = "C#",
                            SkillId = "csharp"
                        },
                        new
                        {
                            Alias = ".NET",
                            SkillId = "dotnet"
                        },
                        new
                        {
                            Alias = "ASP.NET CORE",
                            SkillId = "aspnet-core"
                        },
                        new
                        {
                            Alias = "ENTITY FRAMEWORK CORE",
                            SkillId = "entity-framework-core"
                        },
                        new
                        {
                            Alias = "REACT",
                            SkillId = "react"
                        },
                        new
                        {
                            Alias = "TYPESCRIPT",
                            SkillId = "typescript"
                        },
                        new
                        {
                            Alias = "JAVASCRIPT",
                            SkillId = "javascript"
                        },
                        new
                        {
                            Alias = "POSTGRESQL",
                            SkillId = "postgresql"
                        },
                        new
                        {
                            Alias = "SQL",
                            SkillId = "sql"
                        },
                        new
                        {
                            Alias = "DOCKER",
                            SkillId = "docker"
                        },
                        new
                        {
                            Alias = "GIT",
                            SkillId = "git"
                        },
                        new
                        {
                            Alias = "GITHUB ACTIONS",
                            SkillId = "github-actions"
                        },
                        new
                        {
                            Alias = "PYTHON",
                            SkillId = "python"
                        },
                        new
                        {
                            Alias = "JAVA",
                            SkillId = "java"
                        },
                        new
                        {
                            Alias = "NODE.JS",
                            SkillId = "nodejs"
                        },
                        new
                        {
                            Alias = "EXPRESS",
                            SkillId = "express"
                        },
                        new
                        {
                            Alias = "REST APIS",
                            SkillId = "rest-api"
                        },
                        new
                        {
                            Alias = "DEPENDENCY INJECTION",
                            SkillId = "dependency-injection"
                        },
                        new
                        {
                            Alias = "AUTHENTICATION & AUTHORIZATION",
                            SkillId = "authentication-authorization"
                        },
                        new
                        {
                            Alias = "AUTOMATED TESTING",
                            SkillId = "automated-testing"
                        },
                        new
                        {
                            Alias = "CI/CD",
                            SkillId = "ci-cd"
                        },
                        new
                        {
                            Alias = "AWS",
                            SkillId = "aws"
                        },
                        new
                        {
                            Alias = "EF CORE",
                            SkillId = "entity-framework-core"
                        },
                        new
                        {
                            Alias = "POSTGRES",
                            SkillId = "postgresql"
                        },
                        new
                        {
                            Alias = "CSHARP",
                            SkillId = "csharp"
                        },
                        new
                        {
                            Alias = ".NET WEB API",
                            SkillId = "aspnet-core"
                        },
                        new
                        {
                            Alias = "ASP.NET WEB API",
                            SkillId = "aspnet-core"
                        },
                        new
                        {
                            Alias = "NODE",
                            SkillId = "nodejs"
                        },
                        new
                        {
                            Alias = "REST",
                            SkillId = "rest-api"
                        },
                        new
                        {
                            Alias = "AUTH",
                            SkillId = "authentication-authorization"
                        },
                        new
                        {
                            Alias = "TESTING",
                            SkillId = "automated-testing"
                        });
                });

            modelBuilder.Entity("ProofPath.Infrastructure.Identity.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("ProofPath.Domain.Entities.Credential", b =>
                {
                    b.HasBaseType("ProofPath.Domain.Entities.CandidateFact");

                    b.ToTable("Credentials", (string)null);
                });

            modelBuilder.Entity("ProofPath.Domain.Entities.Education", b =>
                {
                    b.HasBaseType("ProofPath.Domain.Entities.CandidateFact");

                    b.ToTable("Educations", (string)null);
                });

            modelBuilder.Entity("ProofPath.Domain.Entities.Experience", b =>
                {
                    b.HasBaseType("ProofPath.Domain.Entities.CandidateFact");

                    b.ToTable("Experiences", (string)null);
                });

            modelBuilder.Entity("ProofPath.Domain.Entities.Project", b =>
                {
                    b.HasBaseType("ProofPath.Domain.Entities.CandidateFact");

                    b.Property<Guid?>("RepositoryId")
                        .HasColumnType("uuid");

                    b.Property<string>("SourceUrl")
                        .HasColumnType("text");

                    b.HasIndex("RepositoryId")
                        .IsUnique()
                        .HasFilter("\"RepositoryId\" IS NOT NULL");

                    b.ToTable("Projects", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("ProofPath.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("ProofPath.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProofPath.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("ProofPath.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ProofPath.Domain.Entities.AnalysisJob", b =>
                {
                    b.HasOne("ProofPath.Domain.Entities.CandidateProfile", null)
                        .WithMany()
                        .HasForeignKey("CandidateProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ProofPath.Domain.Entities.BehavioralEvidenceItem", b =>
                {
                    b.HasOne("ProofPath.Domain.Entities.CandidateProfile", null)
                        .WithMany()
                        .HasForeignKey("CandidateProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProofPath.Domain.Entities.ResumeExtraction", null)
                        .WithMany()
                        .HasForeignKey("ResumeExtractionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ProofPath.Domain.Entities.CandidateFact", b =>
                {
                    b.HasOne("ProofPath.Domain.Entities.CandidateProfile", null)
                        .WithMany()
                        .HasForeignKey("CandidateProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProofPath.Domain.Entities.ResumeExtraction", null)
                        .WithMany()
                        .HasForeignKey("ResumeExtractionId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("ProofPath.Domain.Entities.CandidateProfile", b =>
                {
                    b.HasOne("ProofPath.Infrastructure.Identity.ApplicationUser", null)
                        .WithOne()
                        .HasForeignKey("ProofPath.Domain.Entities.CandidateProfile", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ProofPath.Domain.Entities.ConnectedAccount", b =>
                {
                    b.HasOne("ProofPath.Domain.Entities.CandidateProfile", null)
                        .WithMany()
                        .HasForeignKey("CandidateProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ProofPath.Domain.Entities.EvidenceItem", b =>
                {
                    b.HasOne("ProofPath.Domain.Entities.CandidateProfile", null)
                        .WithMany()
                        .HasForeignKey("CandidateProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProofPath.Domain.Entities.Project", null)
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("ProofPath.Domain.Entities.RepositoryAnalysis", null)
                        .WithMany()
                        .HasForeignKey("RepositoryAnalysisId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("ProofPath.Domain.Entities.ResumeExtraction", null)
                        .WithMany()
                        .HasForeignKey("ResumeExtractionId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("ProofPath.Domain.Entities.Skill", null)
                        .WithMany()
                        .HasForeignKey("SkillId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("ProofPath.Domain.Entities.GitHubConnectionAttempt", b =>
                {
                    b.HasOne("ProofPath.Domain.Entities.CandidateProfile", null)
                        .WithMany()
                        .HasForeignKey("CandidateProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ProofPath.Domain.Entities.GitHubInstallation", b =>
                {
                    b.HasOne("ProofPath.Domain.Entities.ConnectedAccount", null)
                        .WithOne()
                        .HasForeignKey("ProofPath.Domain.Entities.GitHubInstallation", "ConnectedAccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ProofPath.Domain.Entities.Job", b =>
                {
                    b.HasOne("ProofPath.Domain.Entities.CandidateProfile", null)
                        .WithMany()
                        .HasForeignKey("CandidateProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ProofPath.Domain.Entities.JobRequirement", b =>
                {
                    b.HasOne("ProofPath.Domain.Entities.RequirementSet", null)
                        .WithMany()
                        .HasForeignKey("RequirementSetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProofPath.Domain.Entities.Skill", null)
                        .WithMany()
                        .HasForeignKey("SkillId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("ProofPath.Domain.Entities.JobRequirementExtraction", b =>
                {
                    b.HasOne("ProofPath.Domain.Entities.Job", null)
                        .WithMany()
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ProofPath.Domain.Entities.JobTracking", b =>
                {
                    b.HasOne("ProofPath.Domain.Entities.Job", null)
                        .WithOne()
                        .HasForeignKey("ProofPath.Domain.Entities.JobTracking", "JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ProofPath.Domain.Entities.MatchRecommendation", b =>
                {
                    b.HasOne("ProofPath.Domain.Entities.MatchResult", null)
                        .WithMany()
                        .HasForeignKey("MatchResultId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ProofPath.Domain.Entities.MatchResult", b =>
                {
                    b.HasOne("ProofPath.Domain.Entities.Job", null)
                        .WithMany()
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProofPath.Domain.Entities.RequirementSet", null)
                        .WithMany()
                        .HasForeignKey("RequirementSetId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ProofPath.Domain.Entities.MatchingScoringVersion", null)
                        .WithMany()
                        .HasForeignKey("ScoringVersionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("ProofPath.Domain.Entities.Repository", b =>
                {
                    b.HasOne("ProofPath.Domain.Entities.CandidateProfile", null)
                        .WithMany()
                        .HasForeignKey("CandidateProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProofPath.Domain.Entities.ConnectedAccount", null)
                        .WithMany()
                        .HasForeignKey("ConnectedAccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ProofPath.Domain.Entities.RepositoryAnalysis", b =>
                {
                    b.HasOne("ProofPath.Domain.Entities.AnalysisJob", null)
                        .WithMany()
                        .HasForeignKey("AnalysisJobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProofPath.Domain.Entities.Repository", null)
                        .WithMany()
                        .HasForeignKey("RepositoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ProofPath.Domain.Entities.RequirementMatchEvidenceRecord", b =>
                {
                    b.HasOne("ProofPath.Domain.Entities.RequirementMatchRecord", null)
                        .WithMany()
                        .HasForeignKey("RequirementMatchRecordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ProofPath.Domain.Entities.RequirementMatchRecord", b =>
                {
                    b.HasOne("ProofPath.Domain.Entities.MatchResult", null)
                        .WithMany()
                        .HasForeignKey("MatchResultId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ProofPath.Domain.Entities.RequirementSet", b =>
                {
                    b.HasOne("ProofPath.Domain.Entities.Job", null)
                        .WithMany()
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProofPath.Domain.Entities.JobRequirementExtraction", null)
                        .WithOne()
                        .HasForeignKey("ProofPath.Domain.Entities.RequirementSet", "JobRequirementExtractionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("ProofPath.Domain.Entities.Resume", b =>
                {
                    b.HasOne("ProofPath.Domain.Entities.CandidateProfile", null)
                        .WithMany()
                        .HasForeignKey("CandidateProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ProofPath.Domain.Entities.ResumeExtraction", b =>
                {
                    b.HasOne("ProofPath.Domain.Entities.Resume", null)
                        .WithOne()
                        .HasForeignKey("ProofPath.Domain.Entities.ResumeExtraction", "ResumeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ProofPath.Domain.Entities.SkillAlias", b =>
                {
                    b.HasOne("ProofPath.Domain.Entities.Skill", null)
                        .WithMany()
                        .HasForeignKey("SkillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ProofPath.Domain.Entities.Project", b =>
                {
                    b.HasOne("ProofPath.Domain.Entities.Repository", null)
                        .WithOne()
                        .HasForeignKey("ProofPath.Domain.Entities.Project", "RepositoryId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
